### ISSUE TITLE
100% CPU usage of deluged

### ISSUE THREAD

**Issue by HaleTom** [JohnDoee/deluge-streaming#15]
When steaming a file, CPU usage of `deluged` goes to 100% in linux `top`.

Is there a way to kill a file's streaming server when I no longer want to be streaming a file?

**Comment by JohnDoee** [comment]
Can you try:

* Stream a movie
* Start playing it in a media player
* Stop playing it in a media player
* Set download speed to 1KB/s (or something similar low)
* Check CPU usage.

In order. This is to ensure that it's not hash checking or something else in Deluge that causes the CPU usage.

Also, how powerful is your device running Deluge ? Raspberry Pi ? Seedbox ?

You can't un-stream a movie right now, mostly because it should not matter the movie is being streamed.

**Comment by HaleTom** [comment]
Thanks, I'll get on to that soon. I just noticed that my CPU usage is 30% with the plugin disabled.

I'm running on an Asus UX330, core i5, 7th gen.

**Comment by JohnDoee** [comment]
I fixed a lot of the issues related to looping, better late than never, but should hopefully be better in next release.
