### ISSUE TITLE
reproduction lags and stops for a few seconds with version 0.10.5

### ISSUE THREAD

**Issue by rogergithubbing** [JohnDoee/deluge-streaming#23]
Hello,

I'm getting reproduction lags and frequent stops for a few seconds with version 0.10.5 using deluge v 1.3.15 on Windows 10 x64. If I'm back to your old version 0.9.0, it works perfectly !

What have you changed ? Test it with a low-ram pc with 1.5 GB for example (but, as I said, 0.9.0 works flawlessly)

Thanks,

Roger

**Comment by JohnDoee** [comment]
The libtorrent stuff is pretty problematic because people run different versions, especially when it comes to Linux.

My guess is that you are downloading a piece of the torrent from a slow peer, I've had to change the system to be less aggressive about kicking slow peers because it can create a bit of a vicious circle where it keeps wasting bandwidth and generally slow it all down.

I think I'll add some options with the Deluge 2.0 supported release where you can configure the various aggressiveness.

**Comment by JohnDoee** [comment]
There's a new option in 0.11.0 that allows for aggressive prioritization in config. I think the smartest choice is trying Deluge 2 if possible though.
